# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_moviecast_cast_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieKeywordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(through='recommendation.MovieKeyword', to='recommendation.Keyword'),
        ),
    ]
