# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20170420_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviekeywordcount',
            options={'managed': True},
        ),
    ]
